export function fallbackTranslate(text) {
  return text;
}

const ES_DESCRIPTIONS = {
  "vercel-composition-patterns": "Patrones de composición React de Vercel para crear componentes reutilizables y escalables.",
  "deploy-to-vercel": "Despliega aplicaciones web en Vercel con un solo comando.",
  "vercel-react-best-practices": "Guía de optimización de rendimiento React y Next.js de Vercel Engineering.",
  "vercel-react-native-skills": "Mejores prácticas de React Native y Expo para apps móviles rápidas.",
  "vercel-react-view-transitions": "Implementa transiciones nativas entre rutas con la View Transition API de React.",
  "vercel-cli-with-tokens": "Despliega y gestiona proyectos en Vercel usando autenticación por tokens.",
  "vercel-optimize": "Optimiza costos y rendimiento en proyectos desplegados en Vercel.",
  "web-design-guidelines": "Revisa código UI contra las guías de diseño web de Vercel.",
  "find-skills": "Busca y descubre skills instalables para tus agentes de IA.",
  "claude-api": "Construye, depura y optimiza apps con la API de Claude y SDK de Anthropic.",
  "skill-creator": "Crea, modifica y mejora skills, y mide su rendimiento con evaluaciones.",
  "frontend-design": "Crea interfaces frontend distintivas con diseño de alta calidad.",
  "pptx": "Crea, edita y manipula presentaciones PowerPoint (.pptx).",
  "pdf": "Lee, combina, divide y crea archivos PDF.",
  "docx": "Crea, edita y manipula documentos Word (.docx).",
  "xlsx": "Crea y edita hojas de cálculo Excel (.xlsx, .csv).",
  "canvas-design": "Crea arte visual en PNG y PDF usando filosofía de diseño.",
  "doc-coauthoring": "Guía colaborativa para co-escribir documentación técnica.",
  "internal-comms": "Redacta comunicaciones internas: informes, newsletters, actualizaciones.",
  "brand-guidelines": "Aplica los colores y tipografía oficial de Anthropic a cualquier artefacto.",
  "algorithmic-art": "Crea arte algorítmico con p5.js usando aleatoriedad controlada.",
  "webapp-testing": "Prueba aplicaciones web locales con Playwright.",
  "mcp-builder": "Crea servidores MCP de alta calidad para conectar LLMs con APIs externas.",
  "slack-gif-creator": "Crea GIFs animados optimizados para Slack.",
  "theme-factory": "Kit de herramientas para estilizar artefactos con temas personalizables.",
  "web-artifacts-builder": "Crea artefactos HTML complejos con React, Tailwind y shadcn/ui.",
  "template-skill": "Plantilla base para crear nuevas skills desde cero.",
  "supabase-postgres-best-practices": "Optimización y mejores prácticas de PostgreSQL de Supabase.",
  "supabase": "Configura y utiliza Supabase para backend de aplicaciones.",
  "firebase-basics": "Conceptos fundamentales de Firebase para desarrollo de apps.",
  "firebase-auth-basics": "Implementa autenticación de usuarios con Firebase Auth.",
  "firebase-hosting-basics": "Despliega aplicaciones web con Firebase Hosting.",
  "firebase-app-hosting-basics": "Configura y administra Firebase App Hosting.",
  "firebase-data-connect": "Conecta y sincroniza datos con Firebase Data Connect.",
  "developing-genkit-js": "Desarrolla aplicaciones con Genkit para JavaScript.",
  "developing-genkit-dart": "Desarrolla aplicaciones con Genkit para Dart.",
  "skill-creator": "Crea y optimiza skills con evaluaciones de rendimiento.",
  "frontend-design": "Diseña interfaces frontend únicas y de alta calidad.",
  "ttd": "Desarrollo guiado por pruebas (TDD) para código más robusto.",
  "to-prd": "Convierte ideas y conversaciones en documentos de requisitos (PRD).",
  "to-issues": "Convierte documentos en issues de GitHub organizados.",
  "diagnose": "Diagnostica problemas en código y sugiere soluciones.",
  "prototype": "Crea prototipos rápidos para validar ideas.",
  "handoff": "Prepara y entrega documentación para transferencia de proyectos.",
  "setup-matt-pocock-skills": "Configura todas las skills de Matt Pocock en tu proyecto.",
  "write-a-skill": "Guía para escribir nuevas skills siguiendo mejores prácticas.",
  "improve-codebase-architecture": "Analiza y mejora la arquitectura de tu código base.",
  "caveman": "Enfoque minimalista y directo para resolver problemas de código.",
  "caveman-commit": "Crea commits descriptivos y bien estructurados.",
  "caveman-review": "Revisa código con criterios claros y accionables.",
  "caveman-compress": "Comprime y optimiza archivos de proyecto.",
  "caveman-help": "Obtén ayuda rápida sobre comandos y flujos de trabajo.",
  "caveman-stats": "Estadísticas y métricas del proyecto.",
  "cavecrew": "Coordina múltiples agentes para tareas complejas.",
  "impeccable": "Skill de pulido general para mejorar calidad del código.",
  "polish": "Pule y refina código, diseño y documentación.",
  "critique": "Crítica constructiva de código, diseño y arquitectura.",
  "audit": "Auditoría completa de código, seguridad y rendimiento.",
  "animate": "Añade animaciones fluidas a interfaces web.",
  "adapt": "Adapta código entre frameworks y versiones.",
  "clarify": "Clarifica requisitos y especificaciones ambiguas.",
  "typeset": "Formatea y compone documentos con tipografía profesional.",
  "quieter": "Reduce ruido y simplifica código complejo.",
  "overdrive": "Modo de alta productividad para tareas urgentes.",
  "ai-image-generation": "Genera imágenes con IA usando diferentes modelos.",
  "ai-video-generation": "Genera videos con IA a partir de descripciones.",
  "image-to-video": "Convierte imágenes estáticas en videos animados.",
  "face-swap": "Intercambia rostros en imágenes y videos.",
  "image-inpainting": "Rellena y restaura áreas de imágenes.",
  "image-outpainting": "Expande imágenes más allá de sus bordes originales.",
  "video-outpainting": "Expande videos más allá del encuadre original.",
  "relight": "Re-ilumina imágenes y escenas 3D.",
  "video-extend": "Extiende la duración de videos existentes.",
  "elevenlabs-music-generation": "Genera música con IA usando ElevenLabs.",
  "seo-audit": "Auditoría completa de SEO para sitios web.",
  "copywriting": "Redacción persuasiva para marketing y conversión.",
  "content-strategy": "Planifica y organiza estrategias de contenido.",
  "marketing-psychology": "Aplica principios de psicología al marketing.",
  "programmatic-seo": "SEO programático para contenido a escala.",
  "product-marketing-context": "Contexto y estrategia para lanzamiento de productos.",
  "pricing-strategy": "Define y optimiza estrategias de precios.",
  "ai-seo": "Optimización SEO impulsada por inteligencia artificial.",
  "social-content": "Crea contenido optimizado para redes sociales.",
  "copy-editing": "Edición y corrección de textos publicitarios.",
  "marketing-ideas": "Genera ideas creativas para campañas de marketing.",
  "design-taste-frontend": "Frontend con diseño cuidado y atención al detalle visual.",
  "high-end-visual-design": "Diseño visual de alta gama para interfaces premium.",
  "redesign-existing-projects": "Rediseña proyectos existentes con nueva identidad visual.",
  "minimalist-ui": "Interfaces minimalistas y elegantes.",
  "industrial-brutalist-ui": "Interfaces con estética industrial y brutalista.",
  "stitch-design-taste": "Combina diferentes estilos de diseño en una interfaz coherente.",
  "full-output-enforcement": "Asegura que el agente complete toda la salida requerida.",
  "emil-design-eng": "Principios de diseño-engineering de Emil Kowalski.",
  "ui-ux-pro-max": "Patrones avanzados de UI/UX para interfaces complejas.",
  "sleek-design-mobile-apps": "Diseño mobile-first para apps iOS y Android.",
  "next-best-practices": "Mejores prácticas de desarrollo con Next.js.",
  "shadcn": "Componentes UI con shadcn/ui siguiendo mejores prácticas.",
  "browser-use": "Automatiza navegadores web para testing y scraping.",
  "just-scrape": "Extrae datos estructurados de sitios web.",
  "firecrawl": "Rastrea y extrae contenido de sitios web completos.",
  "sentry-cli": "Gestiona proyectos y releases en Sentry.",
  "deploy-to-vercel": "Despliega aplicaciones en Vercel rápidamente.",
  "microsoft-foundry": "Configura y utiliza Microsoft Foundry para IA.",
  "azure-prepare": "Prepara entornos Azure para desarrollo y despliegue.",
  "azure-hosted-copilot-sdk": "Implementa Copilot SDK hospedado en Azure.",
  "azure-compute": "Gestiona recursos de cómputo en Azure.",
  "azure-cloud-migrate": "Migra infraestructura local a Azure Cloud.",
  "azure-quotas": "Gestiona cuotas y límites de Azure.",
  "azure-upgrade": "Actualiza recursos y servicios de Azure.",
  "azure-cost-optimization": "Optimiza costos en infraestructura Azure.",
  "azure-enterprise-infra-planner": "Planifica infraestructura empresarial en Azure.",
  "azure-kubernetes": "Gestiona clusters Kubernetes en Azure (AKS).",
  "azure-cost": "Analiza y monitorea costos de Azure.",
  "azure-observability": "Implementa observabilidad en Azure.",
  "entra-agent-id": "Configura identidad de agente con Microsoft Entra.",
  "airunway-aks-setup": "Configura AKS para AI Runway.",
  "lark-doc": "Crea y gestiona documentos en Lark.",
  "lark-event": "Configura eventos y webhooks en Lark.",
  "lark-approval": "Gestiona flujos de aprobación en Lark.",
  "lark-slides": "Crea presentaciones en Lark Slides.",
  "lark-attendance": "Gestiona asistencia y registros en Lark.",
  "lark-okr": "Configura y gestiona OKRs en Lark.",
  "lark-markdown": "Convierte y edita markdown en Lark.",
  "lark-vc-agent": "Configura agente de videoconferencias en Lark.",
  "nano-banana-edit": "Edita imágenes con precisión usando Nano Banana.",
  "kling-3-0": "Genera contenido multimedia con Kling 3.0.",
  "codex-pet": "Asistente interactivo tipo mascota para Codex.",
  "runcomfy-cli": "Ejecuta flujos de ComfyUI desde línea de comandos.",
  "ace-step": "Herramienta de edición paso a paso para contenido visual.",
  "seedance-v2": "Genera animaciones y transiciones con Seedance v2.",
  "flux-2-klein": "Genera imágenes con Flux 2 Klein.",
  "gsap": "Animaciones web avanzadas con GSAP.",
  "gsap-video-scrub": "Construye un componente de reproducción de video enlazado al scroll (video scrubbing) usando GSAP y ScrollTrigger en cualquier framework frontend moderno.",
  "hyperframes": "Crea animaciones frame a frame con Hyperframes.",
  "hyperframes-cli": "CLI para Hyperframes: crea y gestiona animaciones.",
  "website-to-hyperframes": "Convierte sitios web completos a Hyperframes.",
  "hyperframes-registry": "Gestiona el registro de componentes Hyperframes.",
  "remotion-best-practices": "Mejores prácticas para crear videos con Remotion.",
  "soultrace": "Traza y analiza el flujo de ejecución de aplicaciones.",
  "agentspace": "Orquesta agentes de IA en AgentSpace.",
  "paper-context-resolver": "Resuelve y contextualiza papers académicos de IA.",
  "extract-design-system": "Extrae sistemas de diseño de código existente.",
  "using-superpowers": "Guía para usar superpoderes de Obra.",
  "systematic-debugging": "Depuración sistemática de código complejo.",
  "writing-plans": "Escribe planes detallados de implementación.",
  "subagent-driven-development": "Desarrollo dirigido por subagentes especializados.",
  "executing-plans": "Ejecuta planes de implementación paso a paso.",
  "requesting-code-review": "Solicita revisiones de código efectivas.",
  "receiving-code-review": "Procesa y aplica feedback de revisiones de código.",
  "test-driven-development": "Desarrollo guiado por tests (TDD) completo.",
  "writing-skills": "Guía avanzada para escribir skills efectivas.",
  "dispatching-parallel-agents": "Orquesta agentes en paralelo para tareas simultáneas.",
  "using-git-worktrees": "Gestiona múltiples ramas con Git Worktrees.",
  "verification-before-completion": "Verifica criterios de aceptación antes de completar.",
  "finishing-a-development-branch": "Completa y cierra ramas de desarrollo correctamente.",
  "brainstorming": "Facilita sesiones de lluvia de ideas estructuradas.",
  "marketing-psychology": "Psicología aplicada a estrategias de marketing.",
  "clickup-tasks": "Gestiona tareas y proyectos en ClickUp.",
  "n8n-workflow": "Crea y gestiona flujos de trabajo automatizados con n8n.",
};

export function generateSpanishDescription(name, source, category) {
  if (ES_DESCRIPTIONS[name]) return ES_DESCRIPTIONS[name];

  const sourceNames = {
    "anthropics/skills": "Anthropic",
    "vercel-labs/agent-skills": "Vercel",
    "vercel-labs/skills": "Vercel Labs",
    "microsoft/azure-skills": "Microsoft Azure",
    "mattpocock/skills": "Matt Pocock",
    "supabase/agent-skills": "Supabase",
    "firebase/agent-skills": "Firebase",
    "obra/superpowers": "Obra",
  };

  const readable = name.replace(/[-_]/g, " ");
  const src = sourceNames[source] || source.split("/").pop();

  const phrases = {
    Backend: `Skill backend de ${src} para ${readable}. Implementa APIs y lógica del servidor.`,
    Frontend: `Skill frontend de ${src} para ${readable}. Construye interfaces y componentes web.`,
    Design: `Skill de diseño de ${src} para ${readable}. Crea interfaces visuales atractivas.`,
    Marketing: `Skill de marketing de ${src} para ${readable}. Optimiza campañas y contenido.`,
    Sales: `Skill de ventas de ${src} para ${readable}. Gestiona pipeline y CRM.`,
    Gaming: `Skill de gaming de ${src} para ${readable}. Crea mecánicas y contenido interactivo.`,
    "AI/ML": `Skill de IA/ML de ${src} para ${readable}. Integra modelos y automatización.`,
    DevOps: `Skill de DevOps de ${src} para ${readable}. Automatiza infraestructura y despliegues.`,
    Security: `Skill de seguridad de ${src} para ${readable}. Protege sistemas y datos.`,
    Data: `Skill de datos de ${src} para ${readable}. Analiza y visualiza información.`,
    "Legal/HR": `Skill de Legal/RH de ${src} para ${readable}. Gestiona documentos y procesos.`,
    Support: `Skill de soporte de ${src} para ${readable}. Automatiza atención al cliente.`,
    "Mobile/XR": `Skill mobile/XR de ${src} para ${readable}. Desarrolla apps y experiencias inmersivas.`,
  };

  return phrases[category] || `Skill de ${src} para ${readable}.`;
}
